#!/usr/bin/env python3
"""Writes website/site.json for the product-page kit (_templates/apps/product-page).

Kept as a script rather than hand-edited JSON: five languages side by side per text are easier to
review, and the output is always valid JSON. Run: python3 tools/website/make_site_json.py
"""
import json
import pathlib

CERT = "78f163f0bfcff57e2e7d3212dee8aedb1d3bfdf48ce4c1512bf7801955a1cf38"


def t(en, de, es, it, fr):
    return {"en": en, "de": de, "es": es, "it": it, "fr": fr}


site = {
    "name": "XCam",
    "slug": "x-cam",
    "aliases": ["xcam.celox.io"],
    "repo": "pepperonas/XCam",
    "branch": "main",
    "tagline": "Record with the screen off.",
    "license": "MIT",
    "year": 2026,
    "asset_version": 2,
    "theme_source": "app/src/main/java/io/celox/xcam/ui/theme/Color.kt — XCamDarkColors (generated by tools/color-scheme.mjs)",
    "theme": {
        "bg": "#1a1111",
        "bg-lowest": "#140c0c",
        "surface-low": "#231919",
        "surface": "#271d1d",
        "surface-high": "#322827",
        "surface-highest": "#3d3232",
        "on-bg": "#f0dedd",
        "on-variant": "#d7c1c0",
        "outline": "#a08c8b",
        "outline-variant": "#534342",
        "primary": "#ffb3b0",
        "on-primary": "#68000f",
        "primary-container": "#93001a",
        "on-primary-container": "#ffdad8",
        "secondary-container": "#663c2d",
        "on-secondary-container": "#ffdbcf",
        "tertiary": "#fdb886",
        "accent": "#e5484d",
    },
    "hero": {"bg": "#180815", "width": 2914, "height": 1440},
    "screens": {"width": 1600, "height": 894},
    "ld": {
        "type": "MobileApplication",
        "category": "MultimediaApplication",
        "subcategory": "Video recorder",
        "os": "Android 13 or later (64-bit ARM)",
    },
    "targets": [
        {
            "id": "android",
            "label": "Download APK",
            "short": "APK",
            "asset": "^xcam-v[0-9][0-9A-Za-z.\\-]*\\.apk$",
            "requirement": "Android 13+ · 64-bit ARM",
            "ua": "android",
        }
    ],
    "chips": [],
    "verify_rows": [
        {
            "label": t(
                "Signing certificate SHA-256",
                "SHA-256 des Signaturzertifikats",
                "SHA-256 del certificado de firma",
                "SHA-256 del certificato di firma",
                "SHA-256 du certificat de signature",
            ),
            "value": CERT,
        }
    ],
    "content": {
        "meta": {
            "title": "XCam — Record Video with the Screen Off (Android)",
            "description": "Free Android app that keeps recording video with the screen off. One tap to start, stop from the notification, auto-stop timer. Open source.",
            "og_title": "XCam — Record with the screen off.",
            "og_description": "Start a recording, lock your phone, XCam keeps going. Free, open source, no account, no tracking.",
            "twitter_description": "Free Android app that records video with the screen off. Open source, no account, no tracking.",
            "image_alt": "XCam: a red eagle keeps watch on a camera — watches everything, stays discreet.",
        },
        "summary": (
            "Free, open-source (MIT) Android app that records video in the background with the screen off. "
            "Tap once, lock the phone, and a foreground service keeps recording; stop it in the app, from the "
            "notification or automatically after 5–60 minutes. Recordings are saved as MP4 to Movies/XCam. "
            "Its only network access is an optional update check against x-cam.celox.io. Android 13+, 64-bit ARM, distributed as a signed APK."
        ),
        "meta_fallback": "Newest release · Android 13+ · 64-bit ARM · free, MIT licence",
        "feature_list": [
            "Records video with the screen off (foreground service with wake lock)",
            "Stop from the app, from the notification, or automatically after 5, 15, 30 or 60 minutes",
            "Back or front camera, 720p, 1080p or 4K, with or without sound",
            "Saves MP4 files to Movies/XCam in the phone's gallery",
            "Share and delete recordings, several at once",
            "Built-in player with share and delete",
            "Material 3 Expressive design with light and dark theme and optional wallpaper colours",
            "English and German",
            "No account, no ads, no tracking; the only network access is a switchable update check",
            "Notifies you when a new version is released",
            "Free and open source (MIT)",
        ],
        "limits": [
            "Android 13 or newer on 64-bit ARM only; no iOS, no desktop.",
            "No live preview, no photo mode, no cloud upload — XCam only records to the phone.",
            "Recording people without their consent is illegal in many countries; the user is responsible for lawful use.",
        ],
        "agent_queries": [
            "Download the latest XCam APK",
            "Which Android app records video with the screen off?",
            "How do I verify that the XCam APK is genuine?",
            "What does XCam need to run?",
        ],
        "tags": ["android", "video-recorder", "background-recording", "open-source"],
        "skill_description": (
            "Download, verify and install the newest XCam APK — the free, open-source Android app that "
            "records video with the screen off. Use when someone asks for the app, its latest version, a "
            "download link, or how to check the APK is genuine."
        ),
        "hero.kicker": t(
            "Android · Open source · Free",
            "Android · Open Source · Kostenlos",
            "Android · Código abierto · Gratis",
            "Android · Open source · Gratis",
            "Android · Open source · Gratuit",
        ),
        "hero.title": t(
            "Tap record. <br>Turn the screen off.",
            "Aufnahme tippen. <br>Bildschirm aus.",
            "Toca grabar. <br>Apaga la pantalla.",
            "Tocca registra. <br>Spegni lo schermo.",
            "Touchez enregistrer. <br>Éteignez l’écran.",
        ),
        "hero.lead": t(
            "XCam keeps recording video while your phone is locked — saved straight to your gallery, stopped "
            "whenever you want. No account, no ads, no tracking.",
            "XCam nimmt weiter Video auf, während dein Handy gesperrt ist — direkt in deine Galerie gespeichert, "
            "beendet wann du willst. Kein Konto, keine Werbung, kein Tracking.",
            "XCam sigue grabando vídeo mientras tu teléfono está bloqueado: se guarda directamente en tu galería "
            "y se detiene cuando quieras. Sin cuenta, sin anuncios, sin rastreo.",
            "XCam continua a registrare video mentre il telefono è bloccato: salvato direttamente nella galleria, "
            "fermato quando vuoi. Nessun account, nessuna pubblicità, nessun tracciamento.",
            "XCam continue d’enregistrer la vidéo pendant que votre téléphone est verrouillé — directement dans "
            "votre galerie, arrêtée quand vous voulez. Sans compte, sans pub, sans pistage.",
        ),
        "pl.h": t("Supported", "Unterstützt", "Compatible", "Supportato", "Compatible"),
        "f.h": t(
            "Made for recording without looking",
            "Gemacht fürs Aufnehmen ohne Hinsehen",
            "Hecha para grabar sin mirar",
            "Fatta per registrare senza guardare",
            "Conçue pour enregistrer sans regarder",
        ),
        "features": [
            {
                "t": t(
                    "Keeps recording, screen off",
                    "Nimmt weiter auf, Bildschirm aus",
                    "Sigue grabando con la pantalla apagada",
                    "Continua a registrare a schermo spento",
                    "Continue d’enregistrer, écran éteint",
                ),
                "p": t(
                    "Recording runs in a foreground service with its own wake lock. Lock the phone, put it in your "
                    "pocket — the camera keeps going until you stop it.",
                    "Die Aufnahme läuft in einem Vordergrunddienst mit eigenem Wakelock. Handy sperren, einstecken — "
                    "die Kamera läuft weiter, bis du sie stoppst.",
                    "La grabación se ejecuta en un servicio en primer plano con su propio wake lock. Bloquea el "
                    "teléfono y guárdalo: la cámara sigue hasta que la detengas.",
                    "La registrazione gira in un servizio in primo piano con il proprio wake lock. Blocca il telefono, "
                    "mettilo in tasca: la fotocamera continua finché non la fermi.",
                    "L’enregistrement tourne dans un service de premier plan avec son propre wake lock. Verrouillez le "
                    "téléphone, rangez-le : la caméra continue jusqu’à ce que vous l’arrêtiez.",
                ),
            },
            {
                "t": t(
                    "One button that is its state",
                    "Ein Knopf, der sein Zustand ist",
                    "Un botón que es su propio estado",
                    "Un pulsante che è il suo stato",
                    "Un bouton qui est son état",
                ),
                "p": t(
                    "Idle, the record button is a soft nine-lobed shape; tap it and it morphs into a stop square. "
                    "What you see is what the camera reports — not a guess.",
                    "Im Ruhezustand ist der Aufnahmeknopf eine weiche Neun-Bogen-Form; antippen, und er verwandelt "
                    "sich in ein Stopp-Quadrat. Was du siehst, meldet die Kamera — nicht geraten.",
                    "En reposo, el botón de grabar es una forma suave de nueve lóbulos; tócalo y se transforma en un "
                    "cuadrado de parada. Lo que ves es lo que informa la cámara, no una suposición.",
                    "A riposo il pulsante di registrazione è una forma morbida a nove lobi; toccalo e diventa un "
                    "quadrato di stop. Quello che vedi è ciò che segnala la fotocamera, non una supposizione.",
                    "Au repos, le bouton d’enregistrement est une forme douce à neuf lobes ; touchez-le et il se "
                    "transforme en carré d’arrêt. Ce que vous voyez, c’est ce que signale la caméra — pas une supposition.",
                ),
            },
            {
                "t": t(
                    "Stop from anywhere — or never",
                    "Stoppen von überall — oder gar nicht",
                    "Detén desde cualquier lugar, o nunca",
                    "Ferma da ovunque, o mai",
                    "Arrêtez de partout — ou jamais",
                ),
                "p": t(
                    "End the recording in the app or straight from the notification, or let it stop by itself after "
                    "5, 15, 30 or 60 minutes. A ring around the button fills as the time runs.",
                    "Beende die Aufnahme in der App oder direkt aus der Benachrichtigung, oder lass sie nach 5, 15, 30 "
                    "oder 60 Minuten von selbst enden. Ein Ring um den Knopf füllt sich mit der Zeit.",
                    "Termina la grabación en la app o desde la notificación, o deja que se detenga sola tras 5, 15, 30 "
                    "o 60 minutos. Un anillo alrededor del botón se llena con el tiempo.",
                    "Termina la registrazione nell’app o direttamente dalla notifica, oppure lasciala fermare da sola "
                    "dopo 5, 15, 30 o 60 minuti. Un anello attorno al pulsante si riempie con il tempo.",
                    "Terminez l’enregistrement dans l’appli ou depuis la notification, ou laissez-le s’arrêter seul "
                    "après 5, 15, 30 ou 60 minutes. Un anneau autour du bouton se remplit au fil du temps.",
                ),
            },
            {
                "t": t(
                    "Straight into your gallery",
                    "Direkt in deine Galerie",
                    "Directo a tu galería",
                    "Direttamente nella galleria",
                    "Directement dans votre galerie",
                ),
                "p": t(
                    "Every recording is an MP4 in <em>Movies/XCam</em>. The app lists them by day with thumbnail, "
                    "length and size — share or delete one or several at once.",
                    "Jede Aufnahme ist eine MP4 in <em>Movies/XCam</em>. Die App listet sie nach Tagen mit Vorschau, "
                    "Länge und Größe — teilen oder löschen, einzeln oder mehrere auf einmal.",
                    "Cada grabación es un MP4 en <em>Movies/XCam</em>. La app las ordena por día con miniatura, "
                    "duración y tamaño: comparte o borra una o varias a la vez.",
                    "Ogni registrazione è un MP4 in <em>Movies/XCam</em>. L’app le elenca per giorno con anteprima, "
                    "durata e dimensione: condividi o elimina una o più alla volta.",
                    "Chaque enregistrement est un MP4 dans <em>Movies/XCam</em>. L’appli les classe par jour avec "
                    "miniature, durée et taille — partagez ou supprimez-en un ou plusieurs à la fois.",
                ),
            },
            {
                "t": t(
                    "Your camera, your quality",
                    "Deine Kamera, deine Qualität",
                    "Tu cámara, tu calidad",
                    "La tua fotocamera, la tua qualità",
                    "Votre caméra, votre qualité",
                ),
                "p": t(
                    "Back or front camera, 720p, 1080p or 4K, with or without sound. If a lens cannot do the chosen "
                    "size, XCam steps down instead of failing. Settings survive a restart.",
                    "Rück- oder Frontkamera, 720p, 1080p oder 4K, mit oder ohne Ton. Kann ein Objektiv die gewählte "
                    "Auflösung nicht, geht XCam eine Stufe runter statt zu scheitern. Einstellungen bleiben gespeichert.",
                    "Cámara trasera o frontal, 720p, 1080p o 4K, con o sin sonido. Si una lente no admite la "
                    "resolución elegida, XCam baja un nivel en lugar de fallar. Los ajustes se guardan.",
                    "Fotocamera posteriore o anteriore, 720p, 1080p o 4K, con o senza audio. Se un obiettivo non "
                    "supporta la risoluzione scelta, XCam scende di un livello invece di fallire. Le impostazioni restano salvate.",
                    "Caméra arrière ou avant, 720p, 1080p ou 4K, avec ou sans son. Si un objectif ne gère pas la "
                    "définition choisie, XCam descend d’un cran au lieu d’échouer. Les réglages sont conservés.",
                ),
            },
            {
                "t": t(
                    "Nothing leaves your phone",
                    "Nichts verlässt dein Handy",
                    "Nada sale de tu teléfono",
                    "Niente lascia il telefono",
                    "Rien ne quitte votre téléphone",
                ),
                "p": t(
                    "Recordings are never uploaded. The only connection XCam makes is a check for new versions at "
                    "x-cam.celox.io, and you can switch it off. No account, no ads, no analytics — open source.",
                    "Aufnahmen werden nie hochgeladen. Die einzige Verbindung ist die Prüfung auf neue Versionen bei "
                    "x-cam.celox.io — und die lässt sich abschalten. Kein Konto, keine Werbung, keine Analyse — Open Source.",
                    "Las grabaciones nunca se suben. La única conexión de XCam es comprobar nuevas versiones en "
                    "x-cam.celox.io, y puedes desactivarla. Sin cuenta, sin anuncios, sin analíticas, de código abierto.",
                    "Le registrazioni non vengono mai caricate. L’unica connessione di XCam è il controllo di nuove "
                    "versioni su x-cam.celox.io, e puoi disattivarlo. Nessun account, nessuna pubblicità, nessuna analisi, open source.",
                    "Les enregistrements ne sont jamais envoyés. La seule connexion de XCam vérifie les nouvelles "
                    "versions sur x-cam.celox.io, et vous pouvez la désactiver. Sans compte, sans pub, sans statistiques — open source.",
                ),
            },
        ],
        "s.h": t(
            "Material 3 Expressive, dark and light",
            "Material 3 Expressive, hell und dunkel",
            "Material 3 Expressive, claro y oscuro",
            "Material 3 Expressive, chiaro e scuro",
            "Material 3 Expressive, clair et sombre",
        ),
        "s.alt": t(
            "Four screens: the guided introduction, recording with the time-limit ring, the recordings list and the settings with update notifications",
            "Vier Bildschirme: die geführte Einführung, die Aufnahme mit Zeitlimit-Ring, die Aufnahmeliste und die Einstellungen mit Update-Hinweisen",
            "Cuatro pantallas: la introducción guiada, la grabación con el anillo de límite, la lista de grabaciones y los ajustes con avisos de actualización",
            "Quattro schermate: l’introduzione guidata, la registrazione con l’anello del limite, l’elenco delle registrazioni e le impostazioni con gli avvisi di aggiornamento",
            "Quatre écrans : l’introduction guidée, l’enregistrement avec l’anneau de limite, la liste des enregistrements et les réglages avec les avis de mise à jour",
        ),
        "install": [
            {
                "t": t("Download the APK", "APK herunterladen", "Descarga la APK", "Scarica l’APK", "Téléchargez l’APK"),
                "p": t(
                    "One file for every 64-bit phone with Android 13 or newer — there is nothing to pick.",
                    "Eine Datei für jedes 64-Bit-Handy mit Android 13 oder neuer — es gibt nichts auszuwählen.",
                    "Un solo archivo para cualquier teléfono de 64 bits con Android 13 o posterior: no hay que elegir nada.",
                    "Un solo file per ogni telefono a 64 bit con Android 13 o superiore: non c’è nulla da scegliere.",
                    "Un seul fichier pour tout téléphone 64 bits sous Android 13 ou plus récent — rien à choisir.",
                ),
            },
            {
                "t": t("Allow the install", "Installation erlauben", "Permite la instalación", "Consenti l’installazione", "Autorisez l’installation"),
                "p": t(
                    "Open the file. Android asks once to allow installs from your browser or file manager.",
                    "Öffne die Datei. Android fragt einmal, ob Installationen aus deinem Browser oder Dateimanager erlaubt sind.",
                    "Abre el archivo. Android pregunta una vez si permites instalar desde tu navegador o gestor de archivos.",
                    "Apri il file. Android chiede una volta di consentire le installazioni dal browser o dal file manager.",
                    "Ouvrez le fichier. Android demande une fois d’autoriser les installations depuis votre navigateur ou gestionnaire de fichiers.",
                ),
            },
            {
                "t": t("Allow the camera, record", "Kamera erlauben, aufnehmen", "Permite la cámara y graba", "Consenti la fotocamera, registra", "Autorisez la caméra, enregistrez"),
                "p": t(
                    "A short introduction asks for the camera — microphone and notifications are optional. Then tap the button.",
                    "Eine kurze Einführung fragt nach der Kamera — Mikrofon und Benachrichtigungen sind optional. Dann den Knopf antippen.",
                    "Una breve introducción pide la cámara; el micrófono y las notificaciones son opcionales. Luego toca el botón.",
                    "Una breve introduzione chiede la fotocamera; microfono e notifiche sono facoltativi. Poi tocca il pulsante.",
                    "Une courte introduction demande la caméra — micro et notifications sont facultatifs. Puis touchez le bouton.",
                ),
            },
        ],
        "v.p": t(
            "Every release from 3.0.0 on is signed with this key. Compare with <code>apksigner verify --print-certs</code>.",
            "Jedes Release ab 3.0.0 ist mit diesem Schlüssel signiert. Vergleiche mit <code>apksigner verify --print-certs</code>.",
            "Cada versión desde la 3.0.0 está firmada con esta clave. Compárala con <code>apksigner verify --print-certs</code>.",
            "Ogni versione dalla 3.0.0 è firmata con questa chiave. Confrontala con <code>apksigner verify --print-certs</code>.",
            "Chaque version depuis la 3.0.0 est signée avec cette clé. Comparez avec <code>apksigner verify --print-certs</code>.",
        ),
        "i.note": t(
            "XCam is published as a signed APK on GitHub Releases, not on Google Play. Coming from version 2.x? "
            "Uninstall it once — 3.0.0 has a new signing key. Your recordings stay in <em>Movies/XCam</em>.",
            "XCam wird als signierte APK über GitHub Releases veröffentlicht, nicht bei Google Play. Du hast Version 2.x? "
            "Einmal deinstallieren — 3.0.0 hat einen neuen Signaturschlüssel. Deine Aufnahmen bleiben in <em>Movies/XCam</em>.",
            "XCam se publica como APK firmada en GitHub Releases, no en Google Play. ¿Vienes de la versión 2.x? "
            "Desinstálala una vez: la 3.0.0 tiene una nueva clave de firma. Tus grabaciones se quedan en <em>Movies/XCam</em>.",
            "XCam è pubblicata come APK firmata su GitHub Releases, non su Google Play. Hai la versione 2.x? "
            "Disinstallala una volta: la 3.0.0 ha una nuova chiave di firma. Le registrazioni restano in <em>Movies/XCam</em>.",
            "XCam est publiée en APK signée sur GitHub Releases, pas sur Google Play. Vous avez la version 2.x ? "
            "Désinstallez-la une fois — la 3.0.0 a une nouvelle clé de signature. Vos enregistrements restent dans <em>Movies/XCam</em>.",
        ),
        "faq": [
            {
                "q": t("Is XCam free?", "Ist XCam kostenlos?", "¿XCam es gratis?", "XCam è gratuita?", "XCam est-elle gratuite ?"),
                "a": t(
                    "Yes. It is free and open source under the MIT licence, with no ads, no in-app purchases and no account.",
                    "Ja. Sie ist kostenlos und Open Source unter der MIT-Lizenz, ohne Werbung, ohne In-App-Käufe und ohne Konto.",
                    "Sí. Es gratuita y de código abierto con licencia MIT, sin anuncios, sin compras dentro de la app y sin cuenta.",
                    "Sì. È gratuita e open source con licenza MIT, senza pubblicità, senza acquisti in-app e senza account.",
                    "Oui. Elle est gratuite et open source sous licence MIT, sans pub, sans achats intégrés et sans compte.",
                ),
            },
            {
                "q": t(
                    "Does it really record with the screen off?",
                    "Nimmt sie wirklich bei ausgeschaltetem Bildschirm auf?",
                    "¿De verdad graba con la pantalla apagada?",
                    "Registra davvero a schermo spento?",
                    "Enregistre-t-elle vraiment écran éteint ?",
                ),
                "a": t(
                    "Yes. The recording runs in a camera-and-microphone foreground service that holds a wake lock, so "
                    "it continues when the phone is locked. Android shows a notification while it runs — you can stop "
                    "the recording from there.",
                    "Ja. Die Aufnahme läuft in einem Vordergrunddienst für Kamera und Mikrofon mit Wakelock und läuft "
                    "daher weiter, wenn das Handy gesperrt ist. Android zeigt währenddessen eine Benachrichtigung — dort "
                    "kannst du die Aufnahme auch beenden.",
                    "Sí. La grabación se ejecuta en un servicio en primer plano de cámara y micrófono con wake lock, así "
                    "que continúa con el teléfono bloqueado. Android muestra una notificación mientras tanto; desde ahí "
                    "puedes detenerla.",
                    "Sì. La registrazione gira in un servizio in primo piano per fotocamera e microfono con wake lock, "
                    "quindi continua a telefono bloccato. Android mostra una notifica nel frattempo, da cui puoi fermarla.",
                    "Oui. L’enregistrement tourne dans un service de premier plan caméra et micro avec wake lock, il "
                    "continue donc téléphone verrouillé. Android affiche une notification pendant ce temps — vous pouvez "
                    "l’arrêter depuis celle-ci.",
                ),
            },
            {
                "q": t("What do I need?", "Was brauche ich?", "¿Qué necesito?", "Cosa mi serve?", "De quoi ai-je besoin ?"),
                "a": t(
                    "A phone with Android 13 or newer and a 64-bit ARM processor — practically every phone sold since "
                    "2022. The camera permission is required; microphone and notifications are optional.",
                    "Ein Handy mit Android 13 oder neuer und 64-Bit-ARM-Prozessor — praktisch jedes seit 2022 verkaufte "
                    "Handy. Die Kamera-Berechtigung ist nötig; Mikrofon und Benachrichtigungen sind optional.",
                    "Un teléfono con Android 13 o posterior y procesador ARM de 64 bits: prácticamente cualquiera vendido "
                    "desde 2022. El permiso de cámara es obligatorio; micrófono y notificaciones son opcionales.",
                    "Un telefono con Android 13 o superiore e processore ARM a 64 bit, praticamente ogni telefono venduto "
                    "dal 2022. Il permesso della fotocamera è necessario; microfono e notifiche sono facoltativi.",
                    "Un téléphone sous Android 13 ou plus récent avec un processeur ARM 64 bits — quasiment tout téléphone "
                    "vendu depuis 2022. L’autorisation caméra est requise ; micro et notifications sont facultatifs.",
                ),
            },
            {
                "q": t("How do I update?", "Wie aktualisiere ich?", "¿Cómo actualizo?", "Come aggiorno?", "Comment mettre à jour ?"),
                "a": t(
                    "Download the newest APK from this page and install it over the app — every release from 3.0.0 on "
                    "is signed with the same key. From 3.1.0 on, XCam tells you itself when a new version is out. Only "
                    "from version 2.x you have to uninstall once.",
                    "Lade die neueste APK von dieser Seite und installiere sie über die App — jedes Release ab 3.0.0 ist "
                    "mit demselben Schlüssel signiert. Ab 3.1.0 meldet XCam selbst, wenn eine neue Version da ist. Nur von "
                    "Version 2.x aus musst du einmal deinstallieren.",
                    "Descarga la APK más reciente desde esta página e instálala encima: cada versión desde la 3.0.0 está "
                    "firmada con la misma clave. Desde la 3.1.0, XCam te avisa cuando hay una versión nueva. Solo desde "
                    "la versión 2.x hay que desinstalar una vez.",
                    "Scarica l’APK più recente da questa pagina e installala sopra l’app: ogni versione dalla 3.0.0 è "
                    "firmata con la stessa chiave. Dalla 3.1.0 XCam ti avvisa da sola quando esce una nuova versione. Solo "
                    "dalla versione 2.x devi disinstallare una volta.",
                    "Téléchargez la dernière APK sur cette page et installez-la par-dessus l’appli — chaque version depuis "
                    "la 3.0.0 est signée avec la même clé. Depuis la 3.1.0, XCam vous prévient elle-même d’une nouvelle "
                    "version. Seulement depuis la version 2.x, il faut désinstaller une fois.",
                ),
            },
            {
                "q": t(
                    "Where are my recordings?",
                    "Wo sind meine Aufnahmen?",
                    "¿Dónde están mis grabaciones?",
                    "Dove sono le mie registrazioni?",
                    "Où sont mes enregistrements ?",
                ),
                "a": t(
                    "In <em>Movies/XCam</em> on your phone, as MP4 files — visible in your gallery and in the app's "
                    "Videos tab. Nothing is uploaded anywhere.",
                    "In <em>Movies/XCam</em> auf deinem Handy, als MP4-Dateien — sichtbar in deiner Galerie und im Tab "
                    "Videos der App. Nichts wird irgendwohin hochgeladen.",
                    "En <em>Movies/XCam</em> en tu teléfono, como archivos MP4, visibles en tu galería y en la pestaña "
                    "Videos de la app. No se sube nada a ningún sitio.",
                    "In <em>Movies/XCam</em> sul telefono, come file MP4, visibili nella galleria e nella scheda Video "
                    "dell’app. Nulla viene caricato da nessuna parte.",
                    "Dans <em>Movies/XCam</em> sur votre téléphone, en fichiers MP4 — visibles dans votre galerie et "
                    "dans l’onglet Vidéos de l’appli. Rien n’est envoyé nulle part.",
                ),
            },
            {
                "q": t(
                    "Is the file genuine?",
                    "Ist die Datei echt?",
                    "¿El archivo es auténtico?",
                    "Il file è autentico?",
                    "Le fichier est-il authentique ?",
                ),
                "a": t(
                    "Compare the SHA-256 checksum and the signing certificate above with the downloaded file. The APK is "
                    "built and signed by GitHub Actions from the public source code.",
                    "Vergleiche die SHA-256-Prüfsumme und das Signaturzertifikat oben mit der heruntergeladenen Datei. "
                    "Die APK wird von GitHub Actions aus dem öffentlichen Quellcode gebaut und signiert.",
                    "Compara la suma SHA-256 y el certificado de firma de arriba con el archivo descargado. La APK la "
                    "compila y firma GitHub Actions a partir del código fuente público.",
                    "Confronta il checksum SHA-256 e il certificato di firma qui sopra con il file scaricato. L’APK è "
                    "compilata e firmata da GitHub Actions dal codice sorgente pubblico.",
                    "Comparez l’empreinte SHA-256 et le certificat de signature ci-dessus avec le fichier téléchargé. "
                    "L’APK est compilée et signée par GitHub Actions à partir du code source public.",
                ),
            },
        ],
        "l.h": t(
            "Record responsibly",
            "Verantwortungsvoll aufnehmen",
            "Graba con responsabilidad",
            "Registra in modo responsabile",
            "Enregistrez de façon responsable",
        ),
        "l.p": t(
            "Recording people without their consent is illegal in many countries. XCam is meant for your own "
            "security and documentation — you are responsible for complying with the law where you record.",
            "Menschen ohne ihre Einwilligung aufzunehmen ist in vielen Ländern verboten. XCam ist für deine eigene "
            "Sicherheit und Dokumentation gedacht — du bist dafür verantwortlich, dich an das geltende Recht zu halten.",
            "Grabar a personas sin su consentimiento es ilegal en muchos países. XCam está pensada para tu propia "
            "seguridad y documentación: eres responsable de cumplir la ley allí donde grabes.",
            "Registrare persone senza il loro consenso è illegale in molti paesi. XCam è pensata per la tua sicurezza "
            "e documentazione: sei responsabile del rispetto della legge dove registri.",
            "Filmer des personnes sans leur consentement est illégal dans de nombreux pays. XCam est destinée à votre "
            "propre sécurité et documentation — vous êtes responsable du respect de la loi là où vous filmez.",
        ),
    },
}

out = pathlib.Path(__file__).resolve().parents[2] / "website" / "site.json"
out.write_text(json.dumps(site, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"wrote {out}")
