name: Build and Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK (signed with debug key)
      run: ./gradlew assembleDebug

    - name: Get version name
      id: version
      run: |
        VERSION_NAME=$(grep "versionName" app/build.gradle.kts | awk -F'"' '{print $2}')
        echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT

    - name: List and rename APKs
      run: |
        cd app/build/outputs/apk/debug
        ls -lh
        # Rename all APKs to include version name
        for apk in app-*.apk; do
          if [ -f "$apk" ]; then
            new_name=$(echo "$apk" | sed "s/app-/XCam-${{ steps.version.outputs.version_name }}-/" | sed "s/-debug//")
            mv "$apk" "$new_name"
            echo "Renamed: $apk -> $new_name"
          fi
        done
        ls -lh

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: XCam-APK
        path: app/build/outputs/apk/debug/XCam-*.apk

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/debug/XCam-*.apk
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
