name: Build and Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Get version name
      id: version
      run: |
        VERSION_NAME=$(grep "versionName" app/build.gradle.kts | awk -F'"' '{print $2}')
        echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT

    - name: Rename APK
      run: |
        mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/XCam-${{ steps.version.outputs.version_name }}.apk

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: XCam-APK
        path: app/build/outputs/apk/release/XCam-*.apk

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/XCam-*.apk
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
